import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  tabStrip: { paddingTop: 10, paddingBottom: 6 },
  primaryTabsScroll: { maxHeight: 44, width: '100%' },
  primaryTabsRow: {
    paddingLeft: 12,
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 16,
    paddingBottom: 0,
  },
  primaryTabWrap: {
    paddingVertical: 0,
    paddingHorizontal: 2,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  primaryTabText: { fontSize: 14, lineHeight: 20 },
  underline: { width: 20, height: 3, borderRadius: 2, marginTop: 6 },
  sectionDivider: {
    height: 1,
    marginTop: 0,
    marginBottom: 8,
  },
  secondaryTabsRowWrap: { flexDirection: 'row', alignItems: 'center', maxHeight: 36 },
  secondaryTabsScroll: { maxHeight: 36, flex: 1, minWidth: 0 },
  secondaryTabsRow: {
    paddingLeft: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  secondaryTabWrap: {
    paddingVertical: 4,
    paddingHorizontal: 6,
    flexShrink: 0,
    minWidth: 72,
  },
  secondaryTabText: { fontSize: 13 },
  secondaryEditIcon: { paddingHorizontal: 12, paddingVertical: 8 },
  editMenuBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  editMenuBox: {
    minWidth: 220,
    borderRadius: 12,
    paddingVertical: 8,
    overflow: 'hidden',
  },
  editMenuItem: {
    paddingVertical: 14,
    paddingHorizontal: 20,
  },
  editMenuLabel: { fontSize: 15, fontWeight: '600' },
  chipsScroll: {
    maxHeight: 32,
    marginTop: 8,
    marginBottom: 8,
    width: '100%',
  },
  chipsRow: { paddingLeft: 12, alignItems: 'center' },
  chipsRowWithFilter: { paddingLeft: 12, alignItems: 'center', paddingRight: 8 },
  filterIconWrap: { padding: 8, justifyContent: 'center' },
  optionsFiltersRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 8,
    paddingHorizontal: 12,
    gap: 12,
  },
  optionsDropdown: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    minWidth: 80,
  },
  expiryDropdownButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    gap: 4,
  },
  chooseExpiryModalBox: {
    width: '100%',
    maxWidth: 340,
    maxHeight: '70%',
    borderRadius: 16,
    overflow: 'hidden',
  },
  chooseExpiryTitle: {
    paddingVertical: 16,
    paddingHorizontal: 20,
  },
  chooseExpiryList: { maxHeight: 320 },
  chooseExpiryButtonsRow: {
    flexDirection: 'row',
    padding: 16,
    gap: 12,
  },
  chooseExpiryButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tableHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 28,
  },
  listContent: { paddingBottom: 16 },
  skeletonList: { flex: 1 },
  skeletonRow: { flexDirection: 'row', alignItems: 'center', gap: 16 },
  skeleton: { borderRadius: 4 },
  skeletonTitle: { height: 14, width: '40%' },
  skeletonPrice: { height: 14, width: 80 },
  errorText: { fontSize: 15, textAlign: 'center', marginBottom: 16 },
  retryButton: { paddingVertical: 10, paddingHorizontal: 20 },
  emptyText: { fontSize: 14, textAlign: 'center', marginTop: 24 },
});
